/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Home_Panels;

import UI.Report_Sort;
import UI.Report_Total;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;

/**
 *
 * @author levan
 */
public class Home_Report extends javax.swing.JPanel {

    private JPanel currentPanel = null;
    private final Color originalColor = new Color(204,204,204);
    private final Color hoverColor = new Color(255,255,255);
    private final Color clickColor = new Color(255,255,255);
    
    public Home_Report() {
        initComponents();     
        // Thêm các thành phần mà mình muốn sử dụng các hiệu ứng
        setPanelEvents(pn_Nav_Total);
        setPanelEvents(pn_Nav_SortByYear);
    }
    private void setPanelEvents(JPanel panel) {
        panel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                if (panel != currentPanel) {
                    panel.setBackground(hoverColor);
                }
            }

            @Override
            public void mouseExited(MouseEvent e) {
                if (panel != currentPanel) {
                    panel.setBackground(originalColor);
                }
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                if (currentPanel != null && panel != currentPanel) {
                    currentPanel.setBackground(originalColor);
                }
                panel.setBackground(clickColor);
                currentPanel = panel;
                
                // Gọi phương thức showPanel khi panel được click
                if (panel == pn_Nav_Total) {
                    showPanel(new Report_Total());
                }
            }
        });
    }
    
    public void showPanel(JPanel panel) {
        pn_Main.removeAll();                      // Xóa tất cả các thành phần con hiện tại từ MainPanel
        pn_Main.add(panel, BorderLayout.CENTER);  // Thêm panel mới vào MainPanel
        pn_Main.revalidate();                     // Thông báo cho layout manager rằng bố cục cần được tính toán lại
        pn_Main.repaint();                        // Vẽ lại MainPanel với các thay đổi mới
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_Nav = new javax.swing.JPanel();
        pn_Nav_Total = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pn_Nav_SortByYear = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pn_Main = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new java.awt.BorderLayout());

        pn_Nav.setBackground(new java.awt.Color(204, 204, 204));
        pn_Nav.setPreferredSize(new java.awt.Dimension(1542, 30));
        pn_Nav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_Nav_Total.setBackground(new java.awt.Color(204, 204, 204));
        pn_Nav_Total.setPreferredSize(new java.awt.Dimension(85, 30));
        pn_Nav_Total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_Nav_TotalMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tổng quát");
        jLabel3.setPreferredSize(new java.awt.Dimension(85, 20));
        jLabel3.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout pn_Nav_TotalLayout = new javax.swing.GroupLayout(pn_Nav_Total);
        pn_Nav_Total.setLayout(pn_Nav_TotalLayout);
        pn_Nav_TotalLayout.setHorizontalGroup(
            pn_Nav_TotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_Nav_TotalLayout.setVerticalGroup(
            pn_Nav_TotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_Nav.add(pn_Nav_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pn_Nav_SortByYear.setBackground(new java.awt.Color(204, 204, 204));
        pn_Nav_SortByYear.setPreferredSize(new java.awt.Dimension(200, 30));
        pn_Nav_SortByYear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_Nav_SortByYearMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thống kê doanh thu");
        jLabel2.setPreferredSize(new java.awt.Dimension(190, 20));
        jLabel2.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout pn_Nav_SortByYearLayout = new javax.swing.GroupLayout(pn_Nav_SortByYear);
        pn_Nav_SortByYear.setLayout(pn_Nav_SortByYearLayout);
        pn_Nav_SortByYearLayout.setHorizontalGroup(
            pn_Nav_SortByYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Nav_SortByYearLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_Nav_SortByYearLayout.setVerticalGroup(
            pn_Nav_SortByYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pn_Nav.add(pn_Nav_SortByYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 150, -1));

        add(pn_Nav, java.awt.BorderLayout.PAGE_START);

        pn_Main.setBackground(new java.awt.Color(255, 255, 255));
        pn_Main.setPreferredSize(new java.awt.Dimension(1512, 700));
        pn_Main.setLayout(new java.awt.BorderLayout());
        add(pn_Main, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void pn_Nav_TotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_Nav_TotalMouseClicked
        // TODO add your handling code here:
        showPanel(new Report_Total());
    }//GEN-LAST:event_pn_Nav_TotalMouseClicked

    private void pn_Nav_SortByYearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_Nav_SortByYearMouseClicked
        // TODO add your handling code here:
        showPanel(new Report_Sort());
    }//GEN-LAST:event_pn_Nav_SortByYearMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pn_Main;
    private javax.swing.JPanel pn_Nav;
    private javax.swing.JPanel pn_Nav_SortByYear;
    private javax.swing.JPanel pn_Nav_Total;
    // End of variables declaration//GEN-END:variables
}
