/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DAO.ConnectSQL;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Report_Total extends javax.swing.JPanel {

    private ConnectSQL connectSQL;
    
    /**
     * Creates new form Report_Total
     */
    public Report_Total() {
        initComponents();
        connectSQL = new ConnectSQL();
        loadRevenueData();
        loadSummaryData();
    }
    
    private void loadRevenueData() {
        List<Object[]> data = connectSQL.getRecent7DaysRevenue();
        DefaultTableModel model = (DefaultTableModel) tblLast7Day.getModel();
        model.setRowCount(0); // Clear existing data

        for (Object[] row : data) {
            model.addRow(row);
        }
    }
    
    private void loadSummaryData() {
        int totalGoods = connectSQL.getTotalGoods();
        int totalCustomers = connectSQL.getTotalCustomers();
        int totalStaff = connectSQL.getTotalStaff();

        // Cập nhật các label
        lblQuantityGoods.setText(String.valueOf(totalGoods));
        lblQuantityCilent.setText(String.valueOf(totalCustomers));
        lblQuantityStaff.setText(String.valueOf(totalStaff));
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pn_Goods = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblQuantityGoods = new javax.swing.JLabel();
        pn_Cilent = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblQuantityCilent = new javax.swing.JLabel();
        pn_Staff = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblQuantityStaff = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLast7Day = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1512, 700));
        setLayout(new java.awt.GridBagLayout());

        pn_Goods.setBackground(new java.awt.Color(204, 204, 204));
        pn_Goods.setMaximumSize(new java.awt.Dimension(300, 100));
        pn_Goods.setPreferredSize(new java.awt.Dimension(300, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/package.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("SỐ MẶT HÀNG");

        lblQuantityGoods.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblQuantityGoods.setForeground(new java.awt.Color(0, 153, 0));
        lblQuantityGoods.setText("NUMBER");

        javax.swing.GroupLayout pn_GoodsLayout = new javax.swing.GroupLayout(pn_Goods);
        pn_Goods.setLayout(pn_GoodsLayout);
        pn_GoodsLayout.setHorizontalGroup(
            pn_GoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_GoodsLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(pn_GoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lblQuantityGoods))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_GoodsLayout.setVerticalGroup(
            pn_GoodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_GoodsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblQuantityGoods)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 18, 0);
        add(pn_Goods, gridBagConstraints);

        pn_Cilent.setBackground(new java.awt.Color(204, 204, 204));
        pn_Cilent.setMaximumSize(new java.awt.Dimension(300, 100));
        pn_Cilent.setPreferredSize(new java.awt.Dimension(300, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rating.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("SỐ KHÁCH HÀNG");

        lblQuantityCilent.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblQuantityCilent.setForeground(new java.awt.Color(0, 153, 0));
        lblQuantityCilent.setText("NUMBER");

        javax.swing.GroupLayout pn_CilentLayout = new javax.swing.GroupLayout(pn_Cilent);
        pn_Cilent.setLayout(pn_CilentLayout);
        pn_CilentLayout.setHorizontalGroup(
            pn_CilentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_CilentLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(pn_CilentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lblQuantityCilent))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_CilentLayout.setVerticalGroup(
            pn_CilentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_CilentLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblQuantityCilent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 8, 0);
        add(pn_Cilent, gridBagConstraints);

        pn_Staff.setBackground(new java.awt.Color(204, 204, 204));
        pn_Staff.setMaximumSize(new java.awt.Dimension(300, 100));
        pn_Staff.setPreferredSize(new java.awt.Dimension(300, 100));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Staff.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("SỐ NHÂN VIÊN");

        lblQuantityStaff.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblQuantityStaff.setForeground(new java.awt.Color(0, 153, 0));
        lblQuantityStaff.setText("NUMBER");

        javax.swing.GroupLayout pn_StaffLayout = new javax.swing.GroupLayout(pn_Staff);
        pn_Staff.setLayout(pn_StaffLayout);
        pn_StaffLayout.setHorizontalGroup(
            pn_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_StaffLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(pn_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(lblQuantityStaff))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_StaffLayout.setVerticalGroup(
            pn_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_StaffLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblQuantityStaff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 8, 0);
        add(pn_Staff, gridBagConstraints);

        tblLast7Day.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tblLast7Day.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngày", "Sản phẩm đã bán", "Doanh thu"
            }
        ));
        tblLast7Day.setRowHeight(55);
        jScrollPane1.setViewportView(tblLast7Day);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        add(jScrollPane1, gridBagConstraints);

        jPanel1.setMaximumSize(new java.awt.Dimension(2349, 32));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Doanh thu trong 8 ngày qua");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1512, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        add(jPanel1, gridBagConstraints);

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQuantityCilent;
    private javax.swing.JLabel lblQuantityGoods;
    private javax.swing.JLabel lblQuantityStaff;
    private javax.swing.JPanel pn_Cilent;
    private javax.swing.JPanel pn_Goods;
    private javax.swing.JPanel pn_Staff;
    private javax.swing.JTable tblLast7Day;
    // End of variables declaration//GEN-END:variables
}
